/*
 * This file is part of ViaBedrock - https://github.com/RaphiMC/ViaBedrock
 * Copyright (C) 2023-2026 RK_01/RaphiMC and contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package net.raphimc.viabedrock.experimental.resourcepack;

import net.raphimc.viabedrock.api.resourcepack.ResourcePack;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.AtomicMoveNotSupportedException;
import java.nio.file.CopyOption;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

public class JavaPackCache {

    // Bump whenever the Bedrock->Java conversion output changes, so that stale cached packs
    // (generated by an older converter) are naturally missed and regenerated instead of served.
    public static final int CONVERTER_VERSION = 6;
    private static final Pattern SHA1_PATTERN = Pattern.compile("[0-9a-f]{40}");

    private final File cacheFolder;
    private final File artifactsFolder;
    private final Map<String, ValidatedEntry> validatedEntries = new HashMap<>();

    private record FileStamp(long size, long modifiedTime) {
    }

    private record ValidatedEntry(String hash, FileStamp zip, FileStamp metadata, FileStamp artifact) {
    }

    public JavaPackCache(final File cacheFolder) {
        this.cacheFolder = cacheFolder;
        this.cacheFolder.mkdirs();
        this.artifactsFolder = new File(cacheFolder, "artifacts");
        this.artifactsFolder.mkdirs();
    }

    public static String computeCacheKey(final Collection<ResourcePack> packs, final boolean supportsFreeRotation) {
        final String raw = packs.stream()
                .map(ResourcePack::key)
                .map(ResourcePack.Key::toString)
                .collect(Collectors.joining(","));
        return sha1Hex(withConverterTag(raw, supportsFreeRotation).getBytes(StandardCharsets.UTF_8));
    }

    public static String computeCacheKey(final ResourcePack.Key[] keys, final boolean supportsFreeRotation) {
        final String raw = Arrays.stream(keys)
                .map(ResourcePack.Key::toString)
                .collect(Collectors.joining(","));
        return sha1Hex(withConverterTag(raw, supportsFreeRotation).getBytes(StandardCharsets.UTF_8));
    }

    // The conversion output depends on the converter version and on the target client's model
    // rotation capability, so both must be part of the cache key. Otherwise a pack converted for a
    // <1.21.11 client (rotations stripped) could be served to a >=1.21.11 client and vice versa.
    private static String withConverterTag(final String raw, final boolean supportsFreeRotation) {
        return raw + "|cv" + CONVERTER_VERSION + "|fr" + supportsFreeRotation;
    }

    public synchronized boolean has(final String cacheKey) {
        try {
            return this.getValidHash(cacheKey) != null;
        } catch (IOException e) {
            return false;
        }
    }

    public synchronized String getHash(final String cacheKey) throws IOException {
        final String hash = this.getValidHash(cacheKey);
        if (hash == null) {
            throw new IOException("Invalid or missing Java resource pack cache entry: " + cacheKey);
        }
        return hash;
    }

    public synchronized byte[] getData(final String cacheKey) throws IOException {
        if (this.getValidHash(cacheKey) == null) {
            throw new IOException("Invalid or missing Java resource pack cache entry: " + cacheKey);
        }
        return Files.readAllBytes(getZipFile(cacheKey).toPath());
    }

    public synchronized String put(final String cacheKey, final byte[] zipData) throws IOException {
        this.validatedEntries.remove(cacheKey);
        final String hash = sha1Hex(zipData);
        final Path zipFile = getZipFile(cacheKey).toPath();
        final Path hashFile = getHashFile(cacheKey).toPath();
        final Path zipTemp = Files.createTempFile(this.cacheFolder.toPath(), cacheKey + "-", ".zip.tmp");
        final Path hashTemp = Files.createTempFile(this.cacheFolder.toPath(), cacheKey + "-", ".sha1.tmp");
        try {
            Files.write(zipTemp, zipData);
            moveAtomically(zipTemp, zipFile);
            this.publishArtifact(zipFile, hash);
            Files.writeString(hashTemp, hash, StandardCharsets.UTF_8);
            moveAtomically(hashTemp, hashFile);
            this.validatedEntries.put(cacheKey, new ValidatedEntry(
                    hash, stamp(zipFile), stamp(hashFile), stamp(this.getArtifactFile(hash).toPath())));
            return hash;
        } finally {
            Files.deleteIfExists(zipTemp);
            Files.deleteIfExists(hashTemp);
        }
    }

    public synchronized String getValidHash(final String cacheKey) throws IOException {
        final Path zipFile = getZipFile(cacheKey).toPath();
        final Path hashFile = getHashFile(cacheKey).toPath();
        if (!Files.isRegularFile(zipFile) || !Files.isRegularFile(hashFile)) {
            return null;
        }

        final String expectedHash = Files.readString(hashFile, StandardCharsets.UTF_8).trim();
        if (!SHA1_PATTERN.matcher(expectedHash).matches()) {
            this.invalidate(cacheKey, zipFile, hashFile);
            return null;
        }

        final Path artifact = this.getArtifactFile(expectedHash).toPath();
        final ValidatedEntry validated = this.validatedEntries.get(cacheKey);
        if (validated != null
                && validated.hash().equals(expectedHash)
                && validated.zip().equals(stamp(zipFile))
                && validated.metadata().equals(stamp(hashFile))
                && Files.isRegularFile(artifact)
                && validated.artifact().equals(stamp(artifact))) {
            return expectedHash;
        }

        if (!expectedHash.equals(sha1Hex(zipFile))) {
            this.invalidate(cacheKey, zipFile, hashFile);
            return null;
        }

        this.publishArtifact(zipFile, expectedHash);
        this.validatedEntries.put(cacheKey, new ValidatedEntry(
                expectedHash, stamp(zipFile), stamp(hashFile), stamp(artifact)));
        return expectedHash;
    }

    private void invalidate(final String cacheKey, final Path zipFile, final Path hashFile) throws IOException {
        this.validatedEntries.remove(cacheKey);
        try {
            Files.deleteIfExists(hashFile);
        } finally {
            Files.deleteIfExists(zipFile);
        }
    }

    public File getArtifactFile(final String hash) {
        if (!SHA1_PATTERN.matcher(hash).matches()) {
            throw new IllegalArgumentException("Invalid SHA-1: " + hash);
        }
        return new File(this.artifactsFolder, hash + ".zip");
    }

    private void publishArtifact(final Path cacheZip, final String hash) throws IOException {
        final Path artifact = this.getArtifactFile(hash).toPath();
        if (Files.isRegularFile(artifact)) {
            if (Files.isSameFile(cacheZip, artifact) || hash.equals(sha1Hex(artifact))) {
                return;
            }
        }

        final Path temp = Files.createTempFile(this.artifactsFolder.toPath(), hash + "-", ".zip.tmp");
        try {
            Files.delete(temp);
            try {
                Files.createLink(temp, cacheZip);
            } catch (UnsupportedOperationException | IOException e) {
                Files.copy(cacheZip, temp, StandardCopyOption.REPLACE_EXISTING);
            }
            moveAtomically(temp, artifact);
        } finally {
            Files.deleteIfExists(temp);
        }
    }

    private static void moveAtomically(final Path source, final Path target) throws IOException {
        final CopyOption[] atomicOptions = {StandardCopyOption.ATOMIC_MOVE, StandardCopyOption.REPLACE_EXISTING};
        try {
            Files.move(source, target, atomicOptions);
        } catch (AtomicMoveNotSupportedException e) {
            Files.move(source, target, StandardCopyOption.REPLACE_EXISTING);
        }
    }

    private static FileStamp stamp(final Path path) throws IOException {
        return new FileStamp(Files.size(path), Files.getLastModifiedTime(path).toMillis());
    }

    private File getZipFile(final String cacheKey) {
        return new File(this.cacheFolder, cacheKey + ".zip");
    }

    private File getHashFile(final String cacheKey) {
        return new File(this.cacheFolder, cacheKey + ".sha1");
    }

    private static String sha1Hex(final byte[] data) {
        try {
            final MessageDigest digest = MessageDigest.getInstance("SHA-1");
            final byte[] hash = digest.digest(data);
            final StringBuilder sb = new StringBuilder(hash.length * 2);
            for (byte b : hash) {
                sb.append(String.format("%02x", b));
            }
            return sb.toString();
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }

    private static String sha1Hex(final Path path) throws IOException {
        try {
            final MessageDigest digest = MessageDigest.getInstance("SHA-1");
            try (InputStream input = Files.newInputStream(path)) {
                final byte[] buffer = new byte[64 * 1024];
                int read;
                while ((read = input.read(buffer)) != -1) {
                    digest.update(buffer, 0, read);
                }
            }
            return toHex(digest.digest());
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }

    private static String toHex(final byte[] hash) {
        final StringBuilder sb = new StringBuilder(hash.length * 2);
        for (byte b : hash) {
            sb.append(String.format("%02x", b));
        }
        return sb.toString();
    }

}
